name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Checkout Dependecies
      run: |
        git clone https://github.com/bucanero/dbglogger.git       --depth 1
        git clone https://github.com/bucanero/ps3mapi-lib.git     --depth 1

    - name: Install Build Dependecies
      run: |
        # Fix `make_self: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
        REPO_URL="http://security.debian.org/debian-security/pool/updates/main/o/openssl/"
        #	libssl1.1_1.1.1w-0+deb11u4_amd64.deb
        PACKAGE_PATTERN="libssl1.1.*_amd64.deb"
        FILELIST=$(curl -s "${REPO_URL}" | grep -oP 'href="\K[^"]+' | grep "${PACKAGE_PATTERN}" || true)

        if [ -z "$FILELIST" ]; then
            echo "No packages found."
            exit 1
        fi

        echo "Found packages:"
        echo "$FILELIST"

        NEWEST=$(echo "$FILELIST" | sort -V | tail -n 1)

        if [ -z "$NEWEST" ]; then
            echo "Could not determine newest package."
            exit 1
        fi

        DOWNLOAD_URL="${REPO_URL}${NEWEST}"
        curl -L -O "${DOWNLOAD_URL}"

        if [ $? -eq 0 ]; then
            sudo apt install ./${NEWEST}
        else
            echo "Download failed!"
            exit 1
        fi
        # and missing python2
        # https://askubuntu.com/a/1527884
        sudo apt update
        wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb  
        sudo apt install ./libpython2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb ./libpython2.7-stdlib_2.7.18-13ubuntu1.5_amd64.deb ./python2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb ./python2.7_2.7.18-13ubuntu1.5_amd64.deb

    - name: Set env vars
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "pkg_file=ArtemisPS3-GUI/ArtemisPS3-GUI.pkg" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xz -C ./
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make
        make install

    - name: Install ps3mapi-lib
      working-directory: ps3mapi-lib
      run: |
        make
        make install

    - name: Build Artemis App Package
      working-directory: ArtemisPS3-GUI
      run: |
        make createzip
        make pkg

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: artemis-ps3-build_${{ steps.slug.outputs.sha8 }}
        path: ${{ env.pkg_file }}
        if-no-files-found: error
